name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  
  - type: input
    id: vscode-version
    attributes:
      label: VS Code Version
      description: What version of VS Code are you running?
      placeholder: e.g., 1.93.0
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Extension Version
      description: What version of Pawn Package are you using?
      placeholder: e.g., 1.1.1
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: repository
    attributes:
      label: Repository Information
      description: If applicable, provide the GitHub repository you were trying to download (owner/repo)
      placeholder: e.g., Y-Less/sscanf

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code.
      render: shell 